spring:
  application:
    name: hotelbooking
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelbooking_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: hotel_booking_schema
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/hotelbooking_mongodb?authSource=admin

logging:
  level:
    org.springframework.security: DEBUG
#    org.springframework.kafka: DEBUG
#    org.apache.kafka: DEBUG

app:
  settings:
    kafka:
      consumer:
        group-id: default-group-id-test
      common:
        bootstrap-servers: localhost:9092
        trusted-packages: com.example.hotelbooking.messaging.events