spring:
  application:
    name: hotelbooking
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelbooking_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: hotel_booking_schema

logging:
  level:
    org.springframework.security: DEBUG

app:
  settings:
    kafka:
      consumer:
        group-id: default-group-id
      common:
        bootstrap-servers: localhost:9092
        trusted-packages: com.example.hotelbooking.statistic_layer.messaging