services:
  kafka:
    image: bitnami/kafka:latest
    container_name: cn_kafka
    volumes:
      - v_kafka:/bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CFG_NUM_PARTITIONS: 3
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CFG_LOG4J_ROOT_LOGLEVEL: INFO
  mongodb:
    image: mongo:6.0.8
    container_name: cn_mongoDB
    ports:
      - "27017:27017"
    volumes:
      - v_mongoDB:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: hotelbooking_mongodb
  postgres:
    image: postgres:12.3
    container_name: cn_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - v_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hotelbooking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  v_kafka:
  v_pgdata:
  v_mongoDB: